### ISSUE TITLE
Skill Installation failure

### ISSUE THREAD

**Issue by merps** [btotharye/mycroft-homeassistant#30]
## Expected Behavior

Installation of HomeAssistantSkill for Mycroft

## Steps to Reproduce the Problem

  1. Fresh build of Mycroft Mark1 image (```mark-1_production_20180301_build-18.zip```)
  2. Pairing of Mark1 to http://home.mycroft.ai
  3. Enable SSH on Mark1 via System Menu
  4. Connect via SSH to Mark1
  5. ```sudo su -```
  6. ```su - mycroft```
  7. Installation with ```msm install https://github.com/btotharye/mycroft-homeassistant.git```

#### ```mycroft-skills.log``` output:
```
12:42:48.191 - mycroft.skills.core:load_skill:106 - INFO - ATTEMPTING TO LOAD SKILL: mycroft-homeassistant with ID -745951192
12:42:50.459 - mycroft.skills.core:load_skill:143 - ERROR - Failed to load skill: mycroft-homeassistant
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/skills/core.py", line 115, in load_skill
skill = skill_module.create_skill()
File "/opt/mycroft/skills/mycroft-homeassistant/__init__.py", line 592, in create_skill
return HomeAssistantSkill()
File "/opt/mycroft/skills/mycroft-homeassistant/__init__.py", line 166, in __init__
self._setup()
File "/opt/mycroft/skills/mycroft-homeassistant/__init__.py", line 178, in _setup
int(self.settings.get('portnum')),
ValueError: invalid literal for int() with base 10: ''
```

## Specifications
  - Version: ```mycroft-core 18.2.5```
  - Platform: ```Mycroft Mark1```

**Comment by merps** [comment]
reason I asked the two questions is it has introduced this now:
`10:44:20.869 - mycroft.skills.core:load_skill:143 - ERROR - Failed to load skill: mycroft-homeassistant
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/skills/core.py", line 115, in load_skill
    skill = skill_module.create_skill()
  File "/opt/mycroft/skills/mycroft-homeassistant/__init__.py", line 598, in create_skill
    return HomeAssistantSkill()
  File "/opt/mycroft/skills/mycroft-homeassistant/__init__.py", line 163, in __init__
    super(HomeAssistantSkill, self).__init__(name="HomeAssistantSkill")
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/skills/core.py", line 1112, in __init__
    MycroftSkill.__init__(self, name, emitter)
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/skills/core.py", line 210, in __init__
    self.settings = SkillSettings(self._dir, self.name)
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/skills/settings.py", line 106, in __init__
    self._poll_skill_settings()
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/skills/settings.py", line 401, in _poll_skill_settings
    LOG.error('Failed to fetch skill settings:\n{}'.format(e))
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/util/log.py", line 32, in method
    cls._log(fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.5-py2.7.egg/mycroft/util/log.py", line 96, in _log
    stack = inspect.stack()
  File "/usr/lib/python2.7/inspect.py", line 1055, in stack
    return getouterframes(sys._getframe(1), context)
  File "/usr/lib/python2.7/inspect.py", line 1033, in getouterframes
    framelist.append((frame,) + getframeinfo(frame, context))
  File "/usr/lib/python2.7/inspect.py", line 1008, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/lib/python2.7/inspect.py", line 580, in findsource
    if pat.match(lines[lnum]): break
IndexError: list index out of range
10:44:20.885 - SKILLS - DEBUG - {"data": {"folder": "mycroft-homeassistant", "id": -745951192}, "type": "mycroft.skills.loading_failure", "context": null}`

**Comment by merps** [comment]
correct - fresh build, fresh install...
