### ISSUE TITLE
Install missing fuzzywuzzy

### ISSUE THREAD

**Issue by scottsweb** [btotharye/mycroft-homeassistant#68]
For some reason with a new install of the plugin I was missing fuzzywuzzy. I installed the latest version (17.0.0) and all seems well. I am wondering if 14.0.0 is no longer available.

```Traceback (most recent call last):
  File "/opt/mycroft/mycroft/skills/core.py", line 117, in load_skill
    ('.py', 'rb', imp.PY_SOURCE)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/mycroft/skills/mycroft-homeassistant.btotharye/__init__.py", line 17, in <module>
    from .ha_client import HomeAssistantClient
  File "/opt/mycroft/skills/mycroft-homeassistant.btotharye/ha_client.py", line 2, in <module>
    from fuzzywuzzy import fuzz
ImportError: No module named 'fuzzywuzzy'
```
With it installed manually all seems well on Mycroft 18.8.1

**Comment by andlo** [comment]
Strange.If I remove the skill and remove fuzzywuzzy and then install the skill it installs fuzzywuzzy==14.0 as told by the requerements.txt

Did try upgrading to fuzzywuzzy==0.17.0 but then the skill stoped working - could be other reasons for that so later ill dig into that.

Maybe requerements.txt just should install fuzzywuzzy and not fuzzywuzzy==0.14.0

**Comment by scottsweb** [comment]
It is certainly an odd one. I ended up having to start again with my install and the second time around it all worked perfectly. I am leaning towards a glitch (perhaps a network interruption) rather than a full on bug. I will close this for now as all seems well.
